---
title: "Introduction to Stata"
---

## Tutorial

In class, we will go through a dofile that introduces the basics of using Stata.  Please first download the instructions on using the virutual computer lab and downloading the data in the first link below.  The second link has the dofile itself, which we will download in class inside of the virtual lab.

[{{< fa solid file-export >}} `introstatainst.pdf`](/files/tutorials/introstatainst.pdf)

[{{< fa solid file-export >}} `introtostata.do`](/files/tutorials/introtostata.do)


## Videos

- [StataCorp Instructional Videos](https://www.youtube.com/@statacorp/videos)

The Stata Corporation maintains a large set of instructional videos that, thankfully, are short and to the point.  In this link, there is a search feature that you can use to find specific videos for the command you are looking for.

## Other Resources

- [Stata Cheat Sheets](https://www.stata.com/flyers/stata-cheat-sheets/)

These provide a quick reference sheet for common commands in Stata.  A very valuable resource for both beginners and advanced users.


- [Graphing in Stata](https://www.stata.com/support/faqs/graphics/gph/stata-graphs/)

A useful overview of the different types of graphs in Stata, and how to use them.