<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <title>EC313 - Taxation – index</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-37d47db5aa478727d56bc09752afe6e8.css">
  <link rel="stylesheet" href="captions.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section class="slide level2">

<h1>
The Personal Income Tax
</h1>
<hr>
<h2>
EC313 - Public Economics: Taxation
</h2>
<h2>
Justin Smith
</h2>
<h2>
Wilfrid Laurier University
</h2>
<h2>
Fall 2025
</h2>
<p><img data-src="../../files/img/hexEC313.png" class="absolute" style="top: 300px; left: 900px; width: 550px; "></p>
</section>
<section>
<section id="goals-of-this-section" class="title-slide slide level1">
<h1>Goals of This Section</h1>

</section>
<section id="goals-of-this-section-1" class="slide level2">
<h2>Goals of This Section</h2>
<ul>
<li><p>Outline history of personal income taxes in Canada</p></li>
<li><p>Describe how taxes are calculated</p></li>
<li><p>Discuss different concepts of income</p></li>
<li><p>Discuss tax rates</p></li>
<li><p>Explore other issues in income taxation</p></li>
</ul>
</section></section>
<section>
<section id="history" class="title-slide slide level1">
<h1>History</h1>

</section>
<section id="origins" class="slide level2">
<h2>Origins</h2>
<ul>
<li><p>Income tax first introduced federally in Canada in 1917 to help finance WWI</p>
<ul>
<li>Initially a temporary measure, but became permanent in 1949</li>
</ul></li>
<li><p>Provinces began introducing income taxes earlier, in the late 1800s (BC, PEI)</p>
<ul>
<li>Most others followed after the Great Depression</li>
<li>Newfoundland was last to introduce income tax in 1949</li>
</ul></li>
<li><p>Currently, both federal and provincial governments levy personal income taxes</p>
<ul>
<li>Authority comes from Constitution Act</li>
</ul></li>
</ul>
</section>
<section id="revenues" class="slide level2">
<h2>Revenues</h2>

<img data-src="images/taxrev.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="revenues-1" class="slide level2">
<h2>Revenues</h2>

<img data-src="images/taxrevint.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="other-details" class="slide level2">
<h2>Other Details</h2>
<ul>
<li><p>Canada Revenue Agency (CRA) administers federal and most provincial income taxes</p>
<ul>
<li>Quebec administers its own provincial income tax</li>
</ul></li>
<li><p>Because of this integration, people fill out one tax return for both federal and provincial taxes</p>
<ul>
<li>Except in Quebec, where two returns are filed</li>
</ul></li>
<li><p>Up to 2000 provincial taxes operated on a “tax on tax” system</p>
<ul>
<li>Provincial taxes were a fraction of federal taxes owed</li>
</ul></li>
<li><p>Since then provinces have moved to a “tax on income” system</p>
<ul>
<li>Provincial taxes are calculated on income before federal taxes are deducted</li>
</ul></li>
</ul>
</section>
<section id="other-details-1" class="slide level2">
<h2>Other Details</h2>
<ul>
<li><p>System based on self-assessment</p>
<ul>
<li>Taxpayers are responsible for reporting their income and calculating their taxes owed</li>
</ul></li>
<li><p>Taxpayers have until April 30 of the following year to file their tax returns</p>
<ul>
<li>Penalties apply if taxes are owed</li>
</ul></li>
<li><p>If you don’t earn income, you don’t have to file a tax return</p>
<ul>
<li>But strong incentive to file to claim benefits or credits</li>
<li>About 12% of working age Canadians do not file a tax return</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="computing-personal-income-tax" class="title-slide slide level1">
<h1>Computing Personal Income Tax</h1>

</section>
<section id="tax-forms" class="slide level2">
<h2>Tax Forms</h2>
<ul>
<li><p>The computation of your tax liability can be complicated</p>
<ul>
<li>Income comes from many sources</li>
<li>Many deductions and credits are available</li>
</ul></li>
<li><p>The CRA provides tax forms to help you compute your taxes</p>
<ul>
<li>Forms are available online or in paper format</li>
<li>Many people use tax software to help with the process</li>
</ul></li>
<li><p>The main federal tax form is the T1</p>
<ul>
<li>There are many additional forms (schedules) for specific types of income or deductions</li>
<li>These forms are federal and provincial</li>
</ul></li>
<li><p>Packages available here: <a href="https://www.canada.ca/en/revenue-agency/services/forms-publications/tax-packages-years.html" class="uri">https://www.canada.ca/en/revenue-agency/services/forms-publications/tax-packages-years.html</a></p></li>
</ul>
</section>
<section id="calculating-taxes" class="slide level2">
<h2>Calculating Taxes</h2>
<ul>
<li><p>The tax forms guide you through a series of steps to calculate your taxes</p></li>
<li><p>The process is algorithmic, and can be summarized in six main steps outlined in the next slides</p></li>
<li><p>Some key things to note</p>
<ul>
<li>Not all income sources are taxable
<ul>
<li>Gifts, inheritances, lottery winnings, strike pay, legal settlements, first nations income on reserve, capital gains on principal residence, refundable tax credits are not taxable</li>
</ul></li>
<li>Not all income from taxable sources is subject to tax
<ul>
<li>Certain income is deducted</li>
<li>Deductions happen for different reasons</li>
</ul></li>
<li>Taxes are remitted to the government through withholding at source
<ul>
<li>So at end of the year you pay the difference or get a refund</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="step-1-calculate-total-income" class="slide level2">
<h2>Step 1: Calculate Total Income</h2>

<img data-src="images/step1.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="step-2-calculate-net-income" class="slide level2">
<h2>Step 2: Calculate Net Income</h2>
<p><img data-src="images/step2a.png" class="quarto-figure quarto-figure-center"> <img data-src="images/step2b.png" class="quarto-figure quarto-figure-center"></p>
</section>
<section id="step-3-calculate-taxable-income" class="slide level2">
<h2>Step 3: Calculate Taxable Income</h2>

<img data-src="images/step3.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="step-4-calculate-federal-tax" class="slide level2">
<h2>Step 4: Calculate Federal Tax</h2>

<img data-src="images/step4.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="step-5-calculate-non-refundable-credits" class="slide level2">
<h2>Step 5: Calculate Non-Refundable Credits</h2>

<img data-src="images/step5.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="step-6-calculate-provincial-tax" class="slide level2">
<h2>Step 6: Calculate Provincial Tax</h2>

<img data-src="images/step6.png" class="quarto-figure quarto-figure-center r-stretch"></section></section>
<section>
<section id="concepts-of-income" class="title-slide slide level1">
<h1>Concepts of Income</h1>

</section>
<section id="haig-simons-income" class="slide level2">
<h2>Haig-Simons Income</h2>
<ul>
<li><p>No definition of income in the Income Tax Act</p></li>
<li><p><strong>Haig-Simons definition</strong> is often used in public finance</p>
<ul>
<li>Net increase in ability to consume during a period</li>
<li>Income = Consumption + Additions to Net Wealth</li>
</ul></li>
<li><p>Includes actual and potential increase in consumption ability</p>
<ul>
<li>E.g., unrealized capital gains are included</li>
</ul></li>
<li><p>Also means decreases in consumption ability are negative income</p>
<ul>
<li>E.g., losses on investments are deductible</li>
</ul></li>
</ul>
</section>
<section id="included-items" class="slide level2">
<h2>Included Items</h2>
<ul>
<li><p>Employer pension contributions</p>
<ul>
<li>Adds to pension fund</li>
<li>Increases ability to consume (in the future)</li>
</ul></li>
<li><p>Transfer payments</p>
<ul>
<li>Retirement benefits, unemployment insurance, social assistance, workers’ compensation</li>
<li>All increase ability to consume</li>
</ul></li>
<li><p>Capital gains/losses</p>
<ul>
<li>Increase in wealth from assets</li>
<li>Realized (value gained after sale) and unrealized (value held prior to sale) gains</li>
<li>Increases ability to consume</li>
<li>Losses deducted because they decrease ability to consume</li>
</ul></li>
</ul>
</section>
<section id="included-items-1" class="slide level2">
<h2>Included Items</h2>
<ul>
<li><p>In-kind income</p>
<ul>
<li>Income received as goods/services rather than cash</li>
<li>Employer perks (e.g., company car, subsidized housing)</li>
<li>Free tuition for dependents of university employees</li>
<li>Imputed rent from owner-occupied housing</li>
</ul></li>
<li><p>Gifts and inheritances</p>
<ul>
<li>Increase wealth and ability to consume</li>
<li>Not currently included in income for tax purposes in Canada (but is elsewhere, e.g., US)</li>
</ul></li>
</ul>
</section>
<section id="problems-with-haig-simons" class="slide level2">
<h2>Problems with Haig-Simons</h2>
<ul>
<li><p>This concept of income is sometimes hard to implement in practice.</p></li>
<li><p>Business expenses</p>
<ul>
<li>Supposed to be expenses incurred to earn income</li>
<li>Some expenses are part consumption part part business
<ul>
<li>E.g., meals, travel, home office expenses</li>
</ul></li>
</ul></li>
<li><p>Capital gains/losses</p>
<ul>
<li>Sometimes hard to measure</li>
<li>Easy for financial assets traded on markets</li>
<li>Hard for other assets
<ul>
<li>Cars, wine, jewelry, art, collectibles</li>
<li>Cryptocurrencies and NFTs</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="problems-with-haig-simons-1" class="slide level2">
<h2>Problems with Haig-Simons</h2>
<ul>
<li><p>Imputed rent</p>
<ul>
<li>Hard to measure</li>
<li>Varies by location, type of housing, size, amenities</li>
<li>Also applies to non-housing assets that might be rented</li>
</ul></li>
<li><p>In-kind income</p>
<ul>
<li>Markets exist for some of these, but not for others</li>
<li>Household labour, volunteer work, parenting, merchandise discounts, etc. are hard to value</li>
</ul></li>
</ul>
</section>
<section id="why-public-economists-use-haig-simons" class="slide level2">
<h2>Why Public Economists Use Haig-Simons</h2>
<ul>
<li><p>Haig-Simons income is a comprehensive measure of ability to pay</p>
<ul>
<li>Includes all sources of consumption and accumulation</li>
<li>Forms a good base on which to tax individuals</li>
<li>It is “fair” in that it captures all sources of income</li>
</ul></li>
<li><p>Horizontal and vertical equity</p>
<ul>
<li>We noted that people with the same ability to pay should pay the same amount of tax</li>
<li>People with greater ability to pay should pay more tax</li>
<li>Basing it on this definition uses all income as basis for ability to pay</li>
</ul></li>
<li><p>Efficiency</p>
<ul>
<li>Treats all forms of income the same</li>
<li>No incentives to alter behaviour to avoid tax</li>
</ul></li>
</ul>
</section>
<section id="income-in-canadas-tax-system" class="slide level2">
<h2>Income in Canada’s Tax System</h2>
<ul>
<li><p>Much of the income counted in personal income taxes aligns with Haig-Simons</p></li>
<li><p>But there are some departures</p>
<ul>
<li>Some income sources are excluded (e.g., gifts, inheritances, lottery winnings, employer contributions to benefits)</li>
<li>Some income sources are only partially included (e.g., capital gains)</li>
<li>Some deductions are allowed that do not fit the concept (e.g., RRSP contributions)</li>
</ul></li>
<li><p>Capital gains are a notable departure</p>
<ul>
<li>Only 50% of capital gains are included in income</li>
<li>Gains on principal residences are not counted at all</li>
<li>In the past there were large gains exemptions (i.e.&nbsp;gains below exemption not taxed)</li>
<li>Only realized gains are taxed</li>
</ul></li>
</ul>
</section>
<section id="income-in-canadas-tax-system-1" class="slide level2">
<h2>Income in Canada’s Tax System</h2>
<ul>
<li><p>These departures can lead to differences in asset value over time</p></li>
<li><p>To see this with realized vs unrealized gains, consider this example</p>
<ul>
<li>A person buys an asset for $100</li>
<li>It appreciates in value by 20% per year over the next 5 years</li>
<li>Asset is sold at the end of year 5</li>
<li>Assume a 50% tax rate and an inclusion rate of 50%</li>
<li>We will go over the tax implications of taxing realized versus unrealized gains</li>
</ul></li>
</ul>
</section>
<section id="income-in-canadas-tax-system-2" class="slide level2">
<h2>Income in Canada’s Tax System</h2>
<ul>
<li>Table below illustrates taxation on <strong>realized gains</strong></li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 8%">
<col style="width: 26%">
<col style="width: 10%">
<col style="width: 20%">
<col style="width: 8%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th style="text-align: right;">Start Year Value</th>
<th style="text-align: right;">Gain</th>
<th style="text-align: right;">Taxable Gain</th>
<th style="text-align: right;">Tax</th>
<th style="text-align: right;">End Year Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">120.00</td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: right;">120.00</td>
<td style="text-align: right;">24.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">144.00</td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: right;">144.00</td>
<td style="text-align: right;">28.80</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">172.80</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: right;">172.80</td>
<td style="text-align: right;">34.56</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">207.36</td>
</tr>
<tr class="odd">
<td>5</td>
<td style="text-align: right;">207.36</td>
<td style="text-align: right;">41.47</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">248.83</td>
</tr>
</tbody>
</table>
<ul>
<li>At the end of the 5 years, the gain is $248.83 - $100 = $148.83</li>
<li>Tax paid is $148.83 * 50% * 50% = $37.21</li>
<li>After- tax value is $248.83 - $37.21 = $211.62</li>
<li>After tax gain is $111.62</li>
</ul>
</section>
<section id="income-in-canadas-tax-system-3" class="slide level2">
<h2>Income in Canada’s Tax System</h2>
<ul>
<li>Table below illustrates taxation on <strong>unrealized gains</strong></li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 8%">
<col style="width: 26%">
<col style="width: 10%">
<col style="width: 20%">
<col style="width: 8%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th style="text-align: right;">Start Year Value</th>
<th style="text-align: right;">Gain</th>
<th style="text-align: right;">Taxable Gain</th>
<th style="text-align: right;">Tax</th>
<th style="text-align: right;">End Year Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">115.00</td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: right;">115.00</td>
<td style="text-align: right;">23.00</td>
<td style="text-align: right;">11.50</td>
<td style="text-align: right;">5.75</td>
<td style="text-align: right;">132.25</td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: right;">132.25</td>
<td style="text-align: right;">26.45</td>
<td style="text-align: right;">13.23</td>
<td style="text-align: right;">6.61</td>
<td style="text-align: right;">152.09</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: right;">152.09</td>
<td style="text-align: right;">30.42</td>
<td style="text-align: right;">15.21</td>
<td style="text-align: right;">7.60</td>
<td style="text-align: right;">174.90</td>
</tr>
<tr class="odd">
<td>5</td>
<td style="text-align: right;">174.90</td>
<td style="text-align: right;">34.98</td>
<td style="text-align: right;">17.49</td>
<td style="text-align: right;">8.75</td>
<td style="text-align: right;">201.14</td>
</tr>
</tbody>
</table>
<ul>
<li>Now the value at the end of year 5 is $201.14</li>
<li>After-tax gain is $201.14 - $100 = $101.14</li>
<li>Total gains are $20 + $23 + $26.45 + $30.42 + $34.98 = $134.85</li>
<li>Tax paid is $5.00 + $5.75 + $6.61 + $7.60 + $8.75 = $134.85 * 50% * 50% = $33.71
<ul>
<li>Less because the gains are smaller</li>
</ul></li>
</ul>
</section>
<section id="income-in-canadas-tax-system-4" class="slide level2">
<h2>Income in Canada’s Tax System</h2>
<ul>
<li><p>Taxation of realized gains locks in investments</p>
<ul>
<li>People may be reluctant to sell assets to avoid paying tax</li>
</ul></li>
<li><p>This can lead to inefficiencies in the economy</p>
<ul>
<li>People hold onto assets that are not the best use of their resources</li>
<li>Capital is not allocated to its most productive use</li>
</ul></li>
<li><p>Conservatives proposed an deferral of taxation for investing in Canadian companies</p>
<ul>
<li>No gains tax if reinvested in Canadian companies</li>
<li>Aimed at reducing lock-in effect and encouraging investment in Canada</li>
</ul></li>
</ul>
</section>
<section id="income-in-canadas-tax-system-5" class="slide level2">
<h2>Income in Canada’s Tax System</h2>
<ul>
<li><p>What if a person holds unrealized gains at death?</p>
<ul>
<li>CRA deems gains realized on date of death</li>
<li>Taxes are owed by the estate</li>
<li>If assets are bequeathed to someone else, the change in asset value since date of death is subject to gains tax</li>
</ul></li>
<li><p>Why preferential treatment of capital gains?</p>
<ul>
<li>Encourages investment and risk-taking</li>
<li>Compensates for deferring consumption</li>
<li>Offsets increased tax burden from inflation (nominal gains)</li>
</ul></li>
</ul>
</section>
<section id="income-in-canadas-tax-system-6" class="slide level2">
<h2>Income in Canada’s Tax System</h2>
<ul>
<li><p>Contributions to pension plans (employee and employer) are not included in income until paid out</p>
<ul>
<li><p>Allows people to defer taxes until retirement</p>
<ul>
<li>Beneficial if people are in lower tax brackets when retired</li>
</ul></li>
<li><p>Interest also not taxed until withdrawn<br>
</p></li>
<li><p>Encourages saving for retirement</p></li>
<li><p>But a departure from Haig-Simons definition of income</p></li>
</ul></li>
<li><p>Finally gifts and inheritances are not taxed</p>
<ul>
<li>By Haig-Simons, they should be included in income because they increase ability to consume</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="tax-deductions-and-credits" class="title-slide slide level1">
<h1>Tax Deductions and Credits</h1>

</section>
<section id="introduction" class="slide level2">
<h2>Introduction</h2>
<ul>
<li><p>We discussed how income is calculated for tax purposes</p></li>
<li><p>There is a difference between</p>
<ul>
<li><p>Total income and taxable income</p>
<ul>
<li><strong>Deductions</strong> exclude some income from being taxed</li>
</ul></li>
<li><p>Taxes owing and taxes payable</p>
<ul>
<li><strong>Credits</strong> reduce taxes owing</li>
</ul></li>
</ul></li>
<li><p>There are various reasons for deductions and credits</p>
<ul>
<li>Social policy goals</li>
<li>Economic efficiency</li>
<li>Equity considerations</li>
</ul></li>
</ul>
</section>
<section id="deductions" class="slide level2">
<h2>Deductions</h2>
<ul>
<li><p><strong>Tax Deduction</strong>: An amount that can be subtracted from total income to arrive at taxable income</p></li>
<li><p>In Canada, the main goals of deductions are to</p>
<ul>
<li>Recognize certain unavoidable expenses to earn income (e.g., child care, moving expenses)</li>
<li>Encourage certain behaviours (e.g., saving for retirement, a home)</li>
<li>Other reasons (e.g., spousal support)</li>
</ul></li>
<li><p>Most deductions are for expenses to earn income</p>
<ul>
<li>E.g., moving expenses, child care, union and professional dues, interest expenses</li>
<li>Applies the tax only to the “net” additions to income after the expenses</li>
</ul></li>
</ul>
</section>
<section id="deductions-1" class="slide level2">
<h2>Deductions</h2>
<ul>
<li><p>Most others are to encourage saving</p>
<ul>
<li>E.g., RRSP contributions, registered pension plan contributions</li>
<li>Tax is not paid on these amounts until withdrawn</li>
<li>Most beneficial when people are in high tax brackets when income is earned, and lower ones when withdrawn</li>
</ul></li>
<li><p>First home buyers plan is deductible <strong>and</strong> not taxed when withdrawn</p>
<ul>
<li>Encourages saving for first home purchase</li>
</ul></li>
<li><p>Some savings plans are <em>not</em> tax deductible but interest grows tax free - Tax Free Savings Plans - Registered Education Savings Plans</p></li>
</ul>
</section>
<section id="deductions-2" class="slide level2">
<h2>Deductions</h2>
<ul>
<li><p>Finally, some deductions exist for other reasons</p>
<ul>
<li>E.g., spousal support payments, child support payments</li>
<li>These payments reduce the income of the payer, who is assumed to have greater ability to pay</li>
<li>Support is included in the income of the receiver</li>
<li>Recognizes who ultimately receives the income and consumes it</li>
</ul></li>
</ul>
</section>
<section id="tax-credits" class="slide level2">
<h2>Tax Credits</h2>
<ul>
<li><p><strong>Tax Credit</strong>: An amount that can be subtracted from taxes owing to arrive at taxes payable</p></li>
<li><p>These are different from deductions</p>
<ul>
<li>Deductions reduce the income that is ultimately taxable</li>
<li>Credits occur after taxes are calculated, and reduce the amount owed</li>
</ul></li>
<li><p>There are two types:</p>
<ul>
<li><strong>Non-refundable tax credits</strong>: Reduce taxes owing, but not below zero</li>
<li><strong>Refundable tax credits</strong>: Can reduce taxes owing below zero, resulting in a refund</li>
</ul></li>
<li><p>There are many credits available for different purposes</p>
<ul>
<li>Encourage behaviour</li>
<li>Recognize certain costs</li>
<li>Equity considerations</li>
</ul></li>
</ul>
</section>
<section id="tax-credits-1" class="slide level2">
<h2>Tax Credits</h2>
<ul>
<li><p>Many credits are 15% of the eligible amount</p>
<ul>
<li>15% is the lowest federal tax rate</li>
<li>So these credits reduce taxes by the same amount as if the eligible amount were deducted from income</li>
</ul></li>
<li><p>Others are different amounts</p>
<ul>
<li>Charitable donations credit is much higher</li>
</ul></li>
</ul>
</section>
<section id="tax-credits-2" class="slide level2">
<h2>Tax Credits</h2>
<ul>
<li><p>Some notable credits are:</p></li>
<li><p>Basic personal amount credit</p>
<ul>
<li>All taxpayers get a credit on the first portion of their income</li>
<li>Recognizes that everyone has some basic consumption needs</li>
</ul></li>
<li><p>Age amount credit</p>
<ul>
<li>For seniors over age 65</li>
<li>Recognizes higher costs of living for seniors</li>
</ul></li>
<li><p>CPP and EI credit</p>
<ul>
<li>Recognizes that these amounts are expenses to earn income</li>
<li>Argument could be made that this is better as a deduction</li>
</ul></li>
</ul>
</section>
<section id="tax-credits-3" class="slide level2">
<h2>Tax Credits</h2>
<ul>
<li><p>Medical expenses</p>
<ul>
<li>Recognizes that medical expenses are necessary consumption</li>
<li>Only expenses above a certain threshold are eligible</li>
</ul></li>
<li><p>Charitable donations</p>
<ul>
<li>Encourages charitable giving</li>
<li>Credit rate increases for donations above certain levels</li>
</ul></li>
<li><p>Canada Workers Benefit</p>
<ul>
<li>A refundable credit for low-income workers</li>
<li>Encourages work and supplements income for low earners</li>
</ul></li>
</ul>
</section>
<section id="tax-credits-4" class="slide level2">
<h2>Tax Credits</h2>
<ul>
<li><p>Boutique credits</p>
<ul>
<li>Targeted at specific groups or behaviours</li>
<li>E.g., credits for digital news subscriptions, home accessibility, volunteer firefighters, fitness</li>
<li>Often criticized for complexity and inequity</li>
</ul></li>
<li><p>GST/HST credit</p>
<ul>
<li>A refundable credit to offset sales taxes paid</li>
<li>Targeted at low and moderate income households</li>
</ul></li>
<li><p>Tuition credit</p>
<ul>
<li>For students to offset costs of education</li>
<li>Unused amounts can be carried forward or transferred to others</li>
</ul></li>
</ul>
</section>
<section id="credits-deductions-and-prices" class="slide level2">
<h2>Credits, Deductions, and Prices</h2>
<ul>
<li><p>One effect of deductions and credits is to alter prices for certain types of consumption</p></li>
<li><p>A good example is charitable donations</p></li>
<li><p>In Ontario, for a $100 donation you would receive a federal credit of $15 and a provincial credit of $5.05</p>
<ul>
<li>Total credit of $20.05</li>
<li>So the effective “price” of a $100 donation is $79.95 after tax savings</li>
</ul></li>
<li><p>In the United States, donors receive a deduction rather than a credit</p>
<ul>
<li>A $100 donation would reduce taxable income by $100</li>
<li>The reduction in the price of the donation depends on the donor’s tax bracket</li>
<li>Someone in the 24% tax bracket avoids $24 in taxes for the $100 donation</li>
<li>So the effective “price” of a $100 donation is $76 after tax savings</li>
<li>Wealthier people (in higher brackets) pay a lower price for donations</li>
</ul></li>
</ul>
</section>
<section id="credits-vs-deductions-fairness" class="slide level2">
<h2>Credits vs Deductions: Fairness</h2>
<ul>
<li><p>Above example highlights a more general issue: benefits from deductions depend on tax bracket</p>
<ul>
<li>People in higher brackets receive more benefit from deductions than those in lower brackets</li>
<li>Some view that as unfair</li>
</ul></li>
<li><p>Many credits in Canada were deductions prior to 1988</p>
<ul>
<li>Converted to credits so that the benefit is the same for all taxpayers</li>
</ul></li>
<li><p>Likely not optimal from an efficiency perspective</p>
<ul>
<li>People differ in their responses to prices</li>
<li>You want to give larger incentives to those who respond more</li>
<li>Credits do not do that</li>
</ul></li>
<li><p>But credits are simpler and viewed as more equitable</p></li>
</ul>
</section>
<section id="tax-expenditures" class="slide level2">
<h2>Tax Expenditures</h2>
<ul>
<li><p>Deductions and credits reduce taxes collected by the government</p>
<ul>
<li>Foregone tax revenue</li>
<li>Money that is not available to fund public services</li>
</ul></li>
<li><p>These can be substantial amounts of money</p></li>
<li><p>This reduction in taxes is viewed as a form of indirect government spending called <strong>tax expenditures</strong></p></li>
</ul>
</section>
<section id="tax-expenditures-1" class="slide level2">
<h2>Tax Expenditures</h2>

<img data-src="images/clipboard-988257517.jpeg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="tax-expenditures-2" class="slide level2">
<h2>Tax Expenditures</h2>
<ul>
<li><p>The Canadian government tracks tax expenditures and reports them annually</p>
<ul>
<li>Current and historical reports here: https://www.canada.ca/en/department-finance/services/publications/federal-tax-expenditures.html</li>
</ul></li>
<li><p>In 2025, projected to be $183 billion federally (6% of GDP)</p>
<ul>
<li>Biggest items: pension deduction, partial inclusion of capital gains, zero-rating of groceries</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="personal-tax-rates-in-canada" class="title-slide slide level1">
<h1>Personal Tax Rates in Canada</h1>

</section>
<section id="introduction-1" class="slide level2">
<h2>Introduction</h2>
<ul>
<li><p>Canada has a progressive tax system</p>
<ul>
<li>Higher income earners pay a larger fraction of their income in taxes</li>
</ul></li>
<li><p>Uses a bracket system</p>
<ul>
<li>Ranges of income where a particular tax rate applies</li>
</ul></li>
<li><p>The tax you pay on an additional dollar of income is called the <strong>marginal tax rate</strong></p>
<ul>
<li>Important for understanding incentives to work, save, invest</li>
<li>Different from the <strong>average tax rate</strong> which is total taxes paid divided by total income</li>
</ul></li>
<li><p>The rate in a particular bracket is the marginal tax rate on each dollar in the bracket</p></li>
</ul>
</section>
<section id="federal-and-provincial-rates" class="slide level2">
<h2>Federal and Provincial Rates</h2>

<img data-src="images/clipboard-779599886.jpeg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="federal-and-provincial-rates-1" class="slide level2">
<h2>Federal and Provincial Rates</h2>

<img data-src="images/clipboard-4098139174.jpeg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="statutory-vs-effective-marginal-taxes" class="slide level2">
<h2>Statutory vs Effective Marginal Taxes</h2>
<ul>
<li><p>The rates shown are <strong>statutory marginal tax rates</strong></p>
<ul>
<li>The rates specified in the tax code</li>
</ul></li>
<li><p>But earning one dollar more income can affect other government programs that affect how much of that dollar you keep</p>
<ul>
<li>E.g., eligibility for benefits, credits, social assistance</li>
<li>These changes can act like a tax or subsidy on additional income</li>
</ul></li>
<li><p>The total effect is called the <strong>effective marginal tax rate</strong></p>
<ul>
<li>Statutory rate plus any changes in benefits/credits/social assistance</li>
</ul></li>
</ul>
</section>
<section id="statutory-vs-effective-marginal-taxes-1" class="slide level2">
<h2>Statutory vs Effective Marginal Taxes</h2>
<ul>
<li><p>Several factors can drive a wedge between statutory and effective marginal tax rates</p>
<ul>
<li><p>Surtaxes: additional taxes applied when income exceeds certain thresholds</p>
<ul>
<li>Canada has mostly eliminated these, but some provinces still have them</li>
</ul></li>
<li><p>Payroll taxes: taxes on earnings to fund social programs (e.g., CPP, EI)</p>
<ul>
<li>These increase the effective marginal tax rate on labour income</li>
</ul></li>
<li><p>Clawbacks: as income increases, eligibility for certain programs decreases</p>
<ul>
<li>E.g., GST/HST credit, Canada Child Benefit, Old Age Security</li>
</ul></li>
</ul></li>
<li><p>What matters for individual decision making is the effective marginal tax rate</p></li>
</ul>
</section>
<section id="statutory-vs-effective-marginal-taxes-2" class="slide level2">
<h2>Statutory vs Effective Marginal Taxes</h2>

<img data-src="images/metr.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="statutory-vs-effective-marginal-taxes-3" class="slide level2">
<h2>Statutory vs Effective Marginal Taxes</h2>

<img data-src="images/clipboard-3611731019.jpeg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="alternative-minimum-tax" class="slide level2">
<h2>Alternative Minimum Tax</h2>
<ul>
<li><p>With the myriad of deductions and credits, it is possible to pay little or no tax despite high income</p>
<ul>
<li>Wealthier people can hire accountants to find ways to reduce tax liability</li>
</ul></li>
<li><p>Canada has an <strong>Alternative Minimum Tax (AMT)</strong> to ensure high-income earners pay a minimum level of tax</p></li>
<li><p>To calculate AMT, taxpayers add back certain deductions and credits to their taxable income</p></li>
<li><p>Applies the normal tax rates to this adjusted income to calculate a minimum tax liability</p></li>
</ul>
</section>
<section id="effective-vs-statutory-taxes-again" class="slide level2">
<h2>Effective vs Statutory Taxes Again</h2>
<ul>
<li><p>We already discussed the differences between statutory and effective marginal tax rates</p></li>
<li><p>This discussion can be broadened to consider these economic factors</p>
<ul>
<li>The economic incidence of a tax is not always on the person who writes the cheque to the government</li>
<li>Taxes involve excess burden (deadweight loss) beyond the tax revenue collected</li>
</ul></li>
<li><p>Simply looking at the statutory tax rates ignores these factors</p></li>
<li><p>Some economists have proposed a <strong>flat tax</strong> as a way to simplify the tax system and reduce excess burden</p>
<ul>
<li>A single tax rate on all income, with few deductions or credits</li>
<li>Would reduce compliance costs and economic distortions</li>
</ul></li>
</ul>
</section>
<section id="effective-vs-statutory-taxes-again-1" class="slide level2">
<h2>Effective vs Statutory Taxes Again</h2>
<ul>
<li><p>Pros of a flat tax would be</p>
<ul>
<li>Simplicity: easier to understand and comply with</li>
<li>Lower compliance costs: less time and money spent on tax preparation</li>
<li>Reduced economic distortions: fewer incentives to alter behaviour to avoid tax</li>
</ul></li>
<li><p>Cons are</p>
<ul>
<li>Equity concerns: flat tax is less progressive, may increase inequality</li>
<li>Some deductions and credits might be eliminated to broaden the tax base</li>
<li>Political feasibility: difficult to implement due to vested interests in current system</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="tax-unit" class="title-slide slide level1">
<h1>Tax Unit</h1>

</section>
<section id="introduction-2" class="slide level2">
<h2>Introduction</h2>
<ul>
<li><p>The current tax unit in Canada is the individual</p>
<ul>
<li>Each person files their own tax return</li>
<li>Income and taxes are calculated separately for each person</li>
<li>Some tax incentives exist for families</li>
</ul></li>
<li><p>Some countries use the family or household as the tax unit</p>
<ul>
<li>Income and taxes are calculated for the family as a whole</li>
<li>Can lead to different tax liabilities compared to individual filing</li>
</ul></li>
<li><p>Which is the better approach?</p></li>
</ul>
</section></section>
<section>
<section id="references" class="title-slide slide level1">
<h1>References</h1>

</section>
<section id="references-1" class="slide level2">
<h2>References</h2>
<ul>
<li><p>Rosen, Harvey S., and Lindsay M. Tedds, and Trevor Tombe, and Jean-Francois Wen, and Tracy Snoddon. Public Finance in Canada. 6th Canadian edition. McGraw-Hill Ryerson, 2023.</p></li>
<li><p>Gruber, Jonathan. Public Finance and Public Policy. 7th edition. Worth Publishers, 2022.</p></li>
<li><p>Bazel, Philip. Marginal Effective Tax Rates for Working Families in Canada. Fraser Institute, 2024.</p></li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true,"theme":"whiteboard","src":"drawings.json"},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>