---
title: "Assignment 1"
---

::: {.callout-warning title="Answer Key"}
You can download the solutions using the links below

[{{< fa solid file-export >}} `a1solutions.qmd`](/assignments/files/a1solutions.qmd)

[{{< fa solid file-export >}} `a1solutions.pdf`](/assignments/files/a1solutions.pdf)
:::

## Description

In this assignment you are asked to manipulate data, estimate statistical relationships, and interpret the findings. The questions are based on course content we have covered up to now, so if you get stuck I highly recommend going back over that material because the questions are closely related. This includes both the lecture notes and the extra material posted to the course website.

You should start this assignment early because it will not be possible (in my opinion) to do well if you start close to the due date. There are parts that you may find difficult; you will want to identify them and leave enough time to ask questions if necessary.

## Instructions

### Template

**The template below contains the assignment questions. Please answer then all within the template in the appropriate place. Replace everything in all caps with your information, and add code where asked.**

When you save the file to your computer, please rename it with your family name and student number, with no spaces.

[{{< fa solid file-export >}} `a1template.qmd`](/assignments/files/a1template.qmd)

### Data analysis

Part of the assignment involves data analysis in R, which you will include as code chunks in the Quarto document. Please make sure all of your analysis is contained in your Quarto document and that it runs properly. Make note of the packages used in the file and ensure you have them installed in RStudio. Also make sure you have a Tex distribution installed on your machine.

Part of the analysis uses the following data file. Save it in the same directory as your template file.

[{{< fa solid file-export >}} `econmath.csv`](/assignments/files/econmath.csv)

A description of all of the variables in the dataset is here

[{{< fa solid file-export >}} `datadesc.pdf`](/assignments/files/datadesc.pdf)

### Submission

When you are finished, you are required to submit two documents according to the following instructions:

-   Your .qmd file containing the completed template file. **Submit this in MyLearningSpace only.**
-   A rendered PDF of your .qmd file. **Submit this in both MyLearningSpace and Gradescope.**

The template is structured to output both the code and the results of the code. Please ensure that this is the case in your rendered PDF because I will grade only that document. I will go to the .qmd file only in cases when something in your PDF does not make sense.

### Plagiarism

This is an independent assignment, which I expect you to complete on your own. It is plagiarism to copy someone else's work verbatim, which includes R code. Any work you submit should be yours only. However, you are encouraged to talk to each other to try to figure out how to do the assignment.
