<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <title>EC313 - Taxation – index</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-37d47db5aa478727d56bc09752afe6e8.css">
  <link rel="stylesheet" href="captions.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section class="slide level2">

<h1>
Consumption Taxation
</h1>
<hr>
<h2>
EC313 - Public Economics: Taxation
</h2>
<h2>
Justin Smith
</h2>
<h2>
Wilfrid Laurier University
</h2>
<h2>
Fall 2025
</h2>
<p><img data-src="../../files/img/hexEC313.png" class="absolute" style="top: 300px; left: 900px; width: 550px; "></p>
</section>
<section>
<section id="goals-of-this-section" class="title-slide slide level1">
<h1>Goals of This Section</h1>

</section>
<section id="goals-of-this-section-1" class="slide level2">
<h2>Goals of This Section</h2>
<ul>
<li><p>Define and discuss types of consumption taxes</p></li>
<li><p>Analyze the efficiency and equity implications of consumption taxes</p></li>
<li><p>Introduce and discuss value added taxes and retail sales taxes</p></li>
<li><p>Summarize Canada’s consumption taxation</p></li>
<li><p>Compare consumption taxes to income taxes</p></li>
</ul>
</section></section>
<section>
<section id="overview" class="title-slide slide level1">
<h1>Overview</h1>

</section>
<section id="introduction" class="slide level2">
<h2>Introduction</h2>
<ul>
<li><p>As we know, purchases of final goods are taxed</p></li>
<li><p>These taxes are called <strong>consumption taxes</strong></p></li>
<li><p>There are several types charged depending on province of residence and the type of good or service purchased</p>
<ul>
<li>They have features that distinguish them from each other</li>
</ul></li>
<li><p>In this section we outline the different types of taxes and discuss their merits</p></li>
</ul>
</section>
<section id="types-of-consumption-taxes" class="slide level2">
<h2>Types of Consumption Taxes</h2>
<ul>
<li><p>Value Added Tax (VAT)</p>
<ul>
<li>Charged at each stage of production based on the value added at that stage</li>
<li>Used globally for taxation of consumption</li>
</ul></li>
<li><p>Retail Sales Tax (RST)</p>
<ul>
<li>Charged only at the point of sale to the final consumer</li>
<li>Used in some provinces in Canada</li>
</ul></li>
<li><p>Excise Taxes</p>
<ul>
<li>Charged on specific goods, often to discourage consumption (e.g., tobacco, alcohol)</li>
<li>Used in all provinces in Canada and by federal government</li>
</ul></li>
<li><p>Custom Duties (tariffs)</p>
<ul>
<li>Charged on goods imported into the country</li>
<li>Used by federal government only</li>
</ul></li>
</ul>
</section>
<section id="revenue-from-consumption-taxes" class="slide level2">
<h2>Revenue from Consumption Taxes</h2>

<img data-src="images/ros55466_1901.jpg" class="quarto-figure quarto-figure-center r-stretch"></section></section>
<section>
<section id="reasons-for-consumption-taxes" class="title-slide slide level1">
<h1>Reasons for Consumption Taxes</h1>

</section>
<section id="administrative-ease" class="slide level2">
<h2>Administrative Ease</h2>
<ul>
<li><p>Relative to other taxes, consumption taxes are easy to administer</p></li>
<li><p>Import duties are collected at the time of importation</p>
<ul>
<li>In the past, relatively few items were imported</li>
<li>Much more now, but still straightforward to collect</li>
</ul></li>
<li><p>Sales taxes are collected from retailers</p>
<ul>
<li><p>Lots of retailers to collect from, but less than for income tax</p></li>
<li><p>Some complications can arise for taxable and non-taxable goods</p>
<ul>
<li>Example: Less than 6 baked goods at a time are taxable, but 6 or more is non-taxable</li>
<li>Some basic groceries are zero rated</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="efficiency" class="slide level2">
<h2>Efficiency</h2>
<ul>
<li><p>Economists argue that consumption taxes are more efficient than income taxes</p></li>
<li><p>Because they do not distort savings behaviour</p>
<ul>
<li>Income taxes reduce the return to saving</li>
<li>Consumption taxes do not affect the return to saving</li>
</ul></li>
<li><p>Example on next slide illustrates this using two period model</p>
<ul>
<li>Assume individuals live for two periods</li>
<li>One person earns income in period 1 and consumes it all</li>
<li>Another person earns income in period 1, saves some, and consumes in period 2</li>
<li>Tax rate on income is 50%, tax rate on consumption is 100%, and interest rate is 10%</li>
</ul></li>
</ul>
</section>
<section id="efficiency-1" class="slide level2">
<h2>Efficiency</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 30%">
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 19%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Inc Tax</strong></td>
<td><strong>Inc Tax</strong></td>
<td><strong>Cons Tax</strong></td>
<td><strong>Cons Tax</strong></td>
</tr>
<tr class="even">
<td><strong>Item</strong></td>
<td><strong>Homer</strong></td>
<td><strong>Marge</strong></td>
<td><strong>Homer</strong></td>
<td><strong>Marge</strong></td>
</tr>
<tr class="odd">
<td><strong>Income in period 1</strong></td>
<td>100.00</td>
<td>100.00</td>
<td>100.00</td>
<td>100.00</td>
</tr>
<tr class="even">
<td><strong>Taxes in period 1</strong></td>
<td>50.00</td>
<td>50.00</td>
<td>50.00</td>
<td>26.19</td>
</tr>
<tr class="odd">
<td><strong>Consumption in period 1</strong></td>
<td>50.00</td>
<td>25.61</td>
<td>50.00</td>
<td>26.19</td>
</tr>
<tr class="even">
<td><strong>Savings in period 1</strong></td>
<td>0.00</td>
<td>24.39</td>
<td>0.00</td>
<td>47.62</td>
</tr>
<tr class="odd">
<td><strong>Interest earnings in period 2</strong></td>
<td>0.00</td>
<td>2.44</td>
<td>0.00</td>
<td>4.76</td>
</tr>
<tr class="even">
<td><strong>Taxes in period 2</strong></td>
<td>0.00</td>
<td>1.22</td>
<td>0.00</td>
<td>26.19</td>
</tr>
<tr class="odd">
<td><strong>Consumption in period 2</strong></td>
<td>0.00</td>
<td>25.61</td>
<td>0.00</td>
<td>26.19</td>
</tr>
<tr class="even">
<td><strong>PDV of taxes</strong></td>
<td>50.00</td>
<td>51.11</td>
<td>50.00</td>
<td>50.00</td>
</tr>
</tbody>
</table>
</section>
<section id="efficiency-2" class="slide level2">
<h2>Efficiency</h2>
<ul>
<li><p>Under the income tax</p>
<ul>
<li><p>Saving is discouraged because the return is less</p></li>
<li><p>Marge pays more in present discounted value of taxes (51.11) than Homer (50.00)</p>
<ul>
<li>So there is a lack of horizontal equity</li>
<li>Marge and Homer are not taxed the same for the same lifetime income</li>
</ul></li>
</ul></li>
<li><p>Under the consumption tax</p>
<ul>
<li><p>Saving is not discouraged because the return is unaffected</p></li>
<li><p>Marge and Homer pay the same present discounted value of taxes (50.00)</p>
<ul>
<li>So there is horizontal equity</li>
<li>Marge and Homer are taxed the same for the same lifetime income</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="efficiency-3" class="slide level2">
<h2>Efficiency</h2>
<ul>
<li><p>There is still an excess burden from the consumption tax</p>
<ul>
<li>Consumption tax distorts choice between consumption and leisure</li>
<li>People will substitute towards leisure, creating excess burden</li>
</ul></li>
<li><p>Studies show that the consumption tax has lower excess burden than income tax</p></li>
</ul>
</section>
<section id="equity" class="slide level2">
<h2>Equity</h2>
<ul>
<li><p>Progressiveness: consumption taxes are often criticized for being regressive</p>
<ul>
<li><p>Lower income individuals spend a larger share of their annual income on consumption</p></li>
<li><p>But, it is less regressive if we consider</p>
<ul>
<li>Lifetime income rather than annual income</li>
<li>Tax credits and transfers that offset regressiveness</li>
</ul></li>
</ul></li>
<li><p>Gender: consumption tax incidents may not be gender neutral</p>
<ul>
<li>Some products targeted to women may have higher prices</li>
<li>A tax levied on product prices may then have a higher incidence for women</li>
</ul></li>
</ul>
</section>
<section id="equity-1" class="slide level2">
<h2>Equity</h2>
<ul>
<li><p>Ability to pay: taxes are levied on actual rather than potential consumption</p>
<ul>
<li>Targeted towards chosen spending patterns rather than ability to pay</li>
<li>A penny-pinching rich person can pay less tax than a poor person</li>
</ul></li>
<li><p>Annual versus lifetime equity: income taxes may generate different lifetime tax burdens</p>
<ul>
<li>Example we covered before with Homer and Marge</li>
<li>Income taxes generated more tax for Marge because she saved</li>
<li>Consumption taxes generate more even lifetime tax burden</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="value-added-taxes" class="title-slide slide level1">
<h1>Value Added Taxes</h1>

</section>
<section id="introduction-1" class="slide level2">
<h2>Introduction</h2>
<ul>
<li><p>Value Added Taxes (VAT) are the most common form of consumption tax globally</p></li>
<li><p>In Canada, the GST and HST are VATs</p></li>
<li><p>Prior to GST, Canada used a the Federal Sales Tax (FST)</p>
<ul>
<li>Sales tax charged at the manufacturing level</li>
</ul></li>
<li><p>The FST had a number of problems</p>
<ul>
<li>Small tax base required high tax rates to collect enough revenue</li>
<li>** Tax Cascading**: taxes charged on manufacturing inputs to other manufactured goods
<ul>
<li>E.g., tax on steel used to make cars</li>
<li>Taxes were charged on the steel and then again on the car</li>
<li>Means taxes were charged on top of taxes</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="introduction-2" class="slide level2">
<h2>Introduction</h2>
<ul>
<li><p>FST was also complex to administer</p></li>
<li><p>GST replaced FST in 1991</p>
<ul>
<li>Broader tax base allowed for lower tax rates</li>
<li>Value added method of taxation eliminated tax cascading</li>
<li>Input tax credits simplified administration for businesses</li>
</ul></li>
<li><p>Original GST rate was 7%</p>
<ul>
<li>Lowered to 6% in 2006, and 5% in 2008</li>
</ul></li>
<li><p>Replaced by HST in some provinces starting in 1997</p>
<ul>
<li>HST combines federal GST and provincial sales tax into single value added tax</li>
<li>Current provinces usng HST are: NS, NB, NL, ON, PEI</li>
</ul></li>
</ul>
</section>
<section id="introduction-3" class="slide level2">
<h2>Introduction</h2>
<ul>
<li><p>BC had HST from 2010 to 2013</p>
<ul>
<li><p>Reverted back to separate GST and PST after a referendum</p></li>
<li><p>Former premier Vander Zalm argued HST was a tax increase</p>
<ul>
<li>Tax applied to more goods and services than PST</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="how-value-added-taxes-work" class="slide level2">
<h2>How Value Added Taxes Work</h2>
<ul>
<li><p>Production of a final good occurs in several stages</p>
<ul>
<li>At each stage, value is added to the good</li>
<li>Value added is the difference between sales revenue and cost of inputs</li>
</ul></li>
<li><p>Example: Production of a table</p>
<ul>
<li>Stage 1: Logger sells logs for $100
<ul>
<li>Value added = $100 - $0 = $100</li>
</ul></li>
<li>Stage 2: Lumber mill buys logs for $100, sells lumber for $150
<ul>
<li>Value added = $150 - $100 = $50</li>
</ul></li>
<li>Stage 3: Furniture maker buys lumber for $150, sells table for $300
<ul>
<li>Value added = $300 - $150 = $150</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="how-value-added-taxes-work-1" class="slide level2">
<h2>How Value Added Taxes Work</h2>
<ul>
<li><p>Taxes are levied on value added at each stage</p></li>
<li><p>Total tax is the sum of taxes at each stage</p></li>
<li><p>Equivalent to a single tax on the final sale price</p></li>
<li><p>Next slide has example of VAT</p>
<ul>
<li>Based on production of bread</li>
</ul></li>
</ul>
</section>
<section id="how-value-added-taxes-work-2" class="slide level2">
<h2>How Value Added Taxes Work</h2>

<img data-src="images/clipboard-1240629291.jpeg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="how-value-added-taxes-work-3" class="slide level2">
<h2>How Value Added Taxes Work</h2>
<ul>
<li><p>How does government collect tax only on value added at each stage?</p></li>
<li><p>Uses an <strong>invoice-credit method</strong></p>
<ul>
<li>At each stage firm pays tax on <em>total</em> sales</li>
<li>But claims a credit for taxes paid by suppliers</li>
</ul></li>
<li><p>Using the bread example:</p>
<ul>
<li>Farmer sells wheat for $400, pays $40 in tax</li>
<li>Miller sells flour for $700, pays $70 in tax, claims $40 credit, remits $30</li>
<li>Baker sells bread for $950, pays $95 in tax, claims $70 credit, remits $25</li>
<li>Grocer sells breat for $1000, pays $100 in tax, claims $95 credit, remits $5</li>
</ul></li>
</ul>
</section>
<section id="implementation-issues" class="slide level2">
<h2>Implementation Issues</h2>
<ul>
<li><p>Some issues make the administration more complex</p>
<ul>
<li><p>Some goods and services are zero rated from VAT</p>
<ul>
<li>Examples: basic food, prescriptiond drugs, medical devices</li>
</ul></li>
<li><p>Firms with annual sales below $30,000 do not remit HST/GST</p></li>
<li><p>Treatment of investment assets (e.g.&nbsp;machines)</p>
<ul>
<li>Not clear whether to include full value, depreciated value, or none of it to compute tax liability</li>
<li>In Canada, usually none of it is included</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="implementation-issues-1" class="slide level2">
<h2>Implementation Issues</h2>
<ul>
<li><p>There is a difference between <strong>zero-rated</strong> and <strong>exempt</strong> goods/services</p>
<ul>
<li>Zero-rated: tax rate is 0%, firms can claim input tax credits</li>
<li>Exempt: no tax charged, firms cannot claim input tax credits</li>
</ul></li>
<li><p>If goods are exempt at retail stage, it appears the same</p>
<ul>
<li>No tax collected on both zero-rated and exempt goods/services</li>
</ul></li>
<li><p>But there are implications for embedded taxes</p>
<ul>
<li>Exempt goods/services have embedded taxes that cannot be claimed back</li>
</ul></li>
</ul>
</section>
<section id="implementation-issues-2" class="slide level2">
<h2>Implementation Issues</h2>

<img data-src="images/clipboard-609976475.jpeg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="efficiency-4" class="slide level2">
<h2>Efficiency</h2>
<ul>
<li><p>We have previously discussed efficient taxes</p>
<ul>
<li>Low excess burden, minimal distortions to behaviour</li>
</ul></li>
<li><p>Is it inefficient to add a VAT when we already have income taxes?</p>
<ul>
<li>If income tax is already optimal, adding VAT creates distortions and inefficiencies</li>
<li>If it is not optimal, VAT may improve efficiency by reducing income tax distortions</li>
</ul></li>
</ul>
</section>
<section id="improvements-to-gst" class="slide level2">
<h2>Improvements to GST</h2>
<ul>
<li><p>Economists like VATs like GST, but citizens do not</p></li>
<li><p>There are ways to improve it</p></li>
<li><p>Harmonization</p>
<ul>
<li>The HST is an improvement over separate GST and PST</li>
<li>Reduces compliance costs for businesses</li>
</ul></li>
<li><p>Compliance costs</p>
<ul>
<li>For GST/HST, firms must track taxes collected and input tax credits</li>
<li>Difficult for firms initially because they did not have appropriate systems</li>
<li>Keeping track of exempt items is also difficult</li>
<li>Need to make improvements to make tax more efficient</li>
</ul></li>
</ul>
</section>
<section id="improvements-to-gst-1" class="slide level2">
<h2>Improvements to GST</h2>

<img data-src="images/clipboard-1461638392.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="improvements-to-gst-2" class="slide level2">
<h2>Improvements to GST</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-4263774221.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-3659338788.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-172103778.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</section>
<section id="improvements-to-gst-3" class="slide level2">
<h2>Improvements to GST</h2>
<ul>
<li><p>Increase tax base by taxing basic groceries?</p>
<ul>
<li>Reduces compliance costs</li>
<li>Politically difficult</li>
</ul></li>
<li><p>Tax-inclusive pricing</p>
<ul>
<li>In other parts of the world, prices include all taxes</li>
<li>In North America, prices are shown before tax</li>
<li>Economists prefer tax to be visible, but inclusive pricing is simpler</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="provincial-sales-taxes" class="title-slide slide level1">
<h1>Provincial Sales Taxes</h1>

</section>
<section id="introduction-4" class="slide level2">
<h2>Introduction</h2>
<ul>
<li><p>As noted, some provinces combine GST and PST</p>
<ul>
<li>GST is a value added tax (VAT)</li>
<li>PST is a retail sales tax (RST)</li>
</ul></li>
<li><p>RSTs are generally charged only at the point of sale to final consumer</p>
<ul>
<li>No input tax credits for businesses</li>
</ul></li>
<li><p>BC, MB, SK, QC all have PST</p>
<ul>
<li>AB has no PST</li>
</ul></li>
</ul>
</section>
<section id="rst-vs-vat" class="slide level2">
<h2>RST vs VAT</h2>
<ul>
<li><p>An RST can be equivalent to VAT when</p>
<ul>
<li>Rate is the same</li>
<li>Tax base is the same</li>
<li>RST is charged only on final sales</li>
</ul></li>
<li><p>In bread example, RST would be charged only by grocer</p>
<ul>
<li>Grocer sells bread for $1000, pays $100 in RST</li>
<li>Sum of VAT amounts is also $100</li>
<li>Difference is that VAT is collected in stages, RST only at final sale</li>
</ul></li>
</ul>
</section>
<section id="rst-vs-vat-1" class="slide level2">
<h2>RST vs VAT</h2>
<ul>
<li><p>They can differ in other circumstances</p></li>
<li><p>Big issue with HST in BC was that it had broader tax base than PST</p></li>
<li><p>Can also sometimes lead to tax cascading</p>
<ul>
<li>If tax is charged on some inputs</li>
</ul></li>
</ul>
</section>
<section id="tax-bases" class="slide level2">
<h2>Tax Bases</h2>
<ul>
<li><p>Unlike the HST, the tax base for PST varies from province to province</p></li>
<li><p>Prepared meals</p>
<ul>
<li>Taxed in MB, SK, QC</li>
<li>Not taxed in BC</li>
</ul></li>
<li><p>Children’s clothing</p>
<ul>
<li>Taxed in SK, QC</li>
<li>Not taxed in BC, MB</li>
</ul></li>
<li><p>All provinces exempt most food</p></li>
<li><p>No economic reason for exemptions; purely political</p></li>
</ul>
</section>
<section id="tax-rates" class="slide level2">
<h2>Tax Rates</h2>

<img data-src="images/clipboard-1059061895.jpeg" class="r-stretch"></section></section>
<section>
<section id="excise-taxes-and-custom-duties" class="title-slide slide level1">
<h1>Excise Taxes and Custom Duties</h1>

</section>
<section id="excise-taxes" class="slide level2">
<h2>Excise Taxes</h2>
<ul>
<li><p>Excise taxes are specific taxes levied on particular goods</p></li>
<li><p>Levied by the federal government and all provinces</p></li>
<li><p>Items listed on next slide</p></li>
<li><p>Reasons for excise taxes</p>
<ul>
<li>Raise revenue</li>
<li>Discourage consumption of harmful goods (e.g., tobacco, alcohol)</li>
<li>Correct for externalities (e.g., gasoline, smoking)</li>
<li>Sin taxes</li>
</ul></li>
</ul>
</section>
<section id="excise-taxes-1" class="slide level2">
<h2>Excise Taxes</h2>

<img data-src="images/clipboard-1693970848.jpeg" class="r-stretch"></section>
<section id="custom-duties" class="slide level2">
<h2>Custom Duties</h2>
<ul>
<li><p>Custom duties (tariffs) are taxes on imported goods</p></li>
<li><p>In the past they were an important source of revenue</p>
<ul>
<li>Not so much today</li>
<li>Lots of trade agreements in place that limit tariffs</li>
</ul></li>
<li><p>Main point of tariffs is to protect domestic industries</p>
<ul>
<li>E.g., steel, dairy, poultry</li>
<li>Can lead to trade wars</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="personal-consumption-taxes" class="title-slide slide level1">
<h1>Personal Consumption Taxes</h1>

</section>
<section id="introduction-5" class="slide level2">
<h2>Introduction</h2>
<ul>
<li><p>Today sales taxes are levied on businesses</p>
<ul>
<li>Tax is usually added on at checkout</li>
<li>But businesses remit to the government</li>
<li>The statutory incidence is on business</li>
</ul></li>
<li><p>Another option would be to levy the tax directly on individuals</p>
<ul>
<li>Individuals would pay tax directly to government</li>
<li>Would file a tax return for consumption</li>
</ul></li>
<li><p>Some argue that it would be better</p>
<ul>
<li>Makes it easier to take personal circumstances into account</li>
</ul></li>
</ul>
</section>
<section id="personal-consumption-tax" class="slide level2">
<h2>Personal Consumption Tax</h2>
<ul>
<li><p>Under this system, people file a tax based on consumption</p></li>
<li><p>Based only on what is consumed</p>
<ul>
<li>Excludes saving (income not consumed)</li>
</ul></li>
<li><p>How would this work?</p></li>
<li><p>A person’s consumption is equivalent to their income minus their change in wealth</p>
<ul>
<li>To compute consumption, add income and subtract changes in wealth</li>
<li>Equivalently, add income and subtract anything not consumed</li>
</ul></li>
<li><p>Like income taxes, there can be deductions and credits</p>
<ul>
<li>E.g., charitable donations, medical expenses</li>
</ul></li>
</ul>
</section>
<section id="personal-consumption-tax-1" class="slide level2">
<h2>Personal Consumption Tax</h2>

<img data-src="images/clipboard-4114351305.jpeg" class="r-stretch"></section>
<section id="hall-rabushka-flax-tax" class="slide level2">
<h2>Hall-Rabushka Flax Tax</h2>
<ul>
<li><p>Hall-Rabushka proposed one (complicated) flat consumption tax</p></li>
<li><p>Works by taxing businesses and individual compensation</p></li>
<li><p>Businesses</p>
<ul>
<li>Pay tax on sales minus purchases from other businesses</li>
<li>Also subtract payments to workers</li>
</ul></li>
<li><p>Individuals</p>
<ul>
<li>Pay tax on wages and salaries minus personal savings</li>
<li>Also subtract investment income (dividends, interest)</li>
</ul></li>
<li><p>Flat tax rate applied to each tax base</p></li>
</ul>
</section>
<section id="hall-rabushka-flax-tax-1" class="slide level2">
<h2>Hall-Rabushka Flax Tax</h2>
<ul>
<li><p>Equivalent to a consumption tax levied on businesses</p>
<ul>
<li>When consumption tax levied on business, it pays tax on sales minus purchases</li>
<li>Wages are embedded in prices, so they are implicitly taxed</li>
<li>With Hall-Rabushka, wages are instead taxed directly at individual level</li>
</ul></li>
<li><p>Only difference is point of collection of certain taxes</p></li>
<li><p>There is no system currently in place that does this</p></li>
</ul>
</section>
<section id="administration-issues" class="slide level2">
<h2>Administration Issues</h2>
<ul>
<li><p>Not feasible if people had to add up all expenditures</p></li>
<li><p>But can work if we impute consumption by income minus saving</p>
<ul>
<li>Would require tracking of savings</li>
<li>Can be done by bank accounts</li>
<li>Potentially problematic for people who save outside of banks</li>
</ul></li>
</ul>
</section>
<section id="administration-issues-1" class="slide level2">
<h2>Administration Issues</h2>
<ul>
<li><p>Some types of consumption are hard to tax</p>
<ul>
<li>Consumption benefits generated by things like housing</li>
<li>E.g., owner-occupied housing</li>
</ul></li>
<li><p>How would we tax this?</p></li>
<li><p>One option: tax prepayment</p>
<ul>
<li>Tax the house (or car, or other durable) at the point of purchase</li>
<li>The value of the durable today is the present value of future consumption services (imputed rent)</li>
<li>The tax charged now should equal to the taxes charged on consumption benefits</li>
</ul></li>
</ul>
</section>
<section id="benefits-of-personal-consumption-tax" class="slide level2">
<h2>Benefits of Personal Consumption Tax</h2>
<ul>
<li><p>Avoid issues of capital gains and depreciation</p>
<ul>
<li>Only consumption is taxed</li>
<li>So no need to track capital gains</li>
</ul></li>
<li><p>Less investment lock-in</p>
<ul>
<li>With income tax, investors may hold onto assets to avoid capital gains tax</li>
<li>With consumption tax, can sell and reinvest without tax consequences</li>
</ul></li>
<li><p>Removes need for separate personal and corporate tax</p></li>
</ul>
</section></section>
<section>
<section id="summary" class="title-slide slide level1">
<h1>Summary</h1>

</section>
<section id="summary-1" class="slide level2">
<h2>Summary</h2>
<ul>
<li><p>Consumption taxes are an important source of government revenue</p></li>
<li><p>Value added taxes (e.g., GST, HST) are the most common form of consumption tax globally</p></li>
<li><p>Retail sales taxes are simpler but can lead to tax cascading</p></li>
<li><p>Excise taxes and custom duties are other forms of consumption taxes</p></li>
<li><p>Consumption taxes are often more efficient than income taxes</p></li>
<li><p>Personal consumption taxes are an alternative way to tax consumption directly</p></li>
</ul>
</section></section>
<section>
<section id="references" class="title-slide slide level1">
<h1>References</h1>

</section>
<section id="references-1" class="slide level2">
<h2>References</h2>
<ul>
<li><p>Rosen, Harvey S., and Lindsay M. Tedds, and Trevor Tombe, and Jean-Francois Wen, and Tracy Snoddon. Public Finance in Canada. 6th Canadian edition. McGraw-Hill Ryerson, 2023.</p></li>
<li><p>Gruber, Jonathan. Public Finance and Public Policy. 7th edition. Worth Publishers, 2022.</p></li>
<li><p>Bazel, Philip. Marginal Effective Tax Rates for Working Families in Canada. Fraser Institute, 2024.</p></li>
<li><p>Hansen, Jeff, and Devan Mescall, and Graham Purse. “Policy Forum: The Effects of Indexation and Inflation on Tax System Design.” Canadian Tax Journal 71, no. 2 (2023): 398-404.</p></li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true,"theme":"whiteboard","src":"drawings.json"},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>